const info = [
    {
        id: 0,
        nume: "Deratizare",
        headerImg: "assets/Deratizare_Hero.jpeg",
        headerText: "Derasovil - Împreună, eliminăm invadatorii neinvitați din locuința ta!",
        infoTitle: "Control Profesional Împotriva Rozătoarelor",
        infoText: "Derasovil este partenerul de încredere în eliminarea eficientă a șobolanilor și șoarecilor. Cu o abordare temeinică și soluții personalizate, ne asigurăm că locuința sau afacerea dvs. sunt protejate. Alegeți Derasovil pentru o deratizare eficace și profesională!",
        CardImg: "assets/Sobolanski.jpeg",
        CardBigWord: "Rozătoarele ", 
        CardText: "sunt purtători de boli și germeni patogeni, reprezentând un pericol pentru sănătatea umană și a animalelor de companie.",
        CardSection1Title: "Metode de Combatere:",
        CardSection1Text: "Deratizarea folosește substanțe chimice, capcane sau măsuri de igienă pentru a elimina rozătoarele din locuința dumneavoastră.",
        CardSection2Title: "Prevenirea reapariției:",
        CardSection2Text: "Este esențială sigilarea acceselor, igienizarea și depozitarea corectă a alimentelor pentru a preveni reinfestarea.",
        CardSection3Title: "Riscuri pentru sănătate:",
        CardSection3Text: "Prezența rozătoarelor poate duce la transmiterea de boli, deteriorarea proprietăților și contaminarea alimentelor și a apei, necesitând o deratizare regulată și eficientă.",
        InfoSection1Icon: "assets/Deratizare_icon1.svg",
        InfoSection1Title: "Siguranță și Responsabilitate",
        InfoSection1Text: "În cadrul Derasovil, punem întotdeauna siguranța clienților noștri pe primul loc. Folosim numai metode și substanțe sigure, care sunt eficiente în eliminarea rozătoarelor, fără a pune în pericol sănătatea oamenilor sau a animalelor de companie. De asemenea, suntem responsabili și respectăm toate reglementările și standardele de mediu în timpul procesului de deratizare, contribuind astfel la protejarea mediului înconjurător.",
        InfoSection1Img: "assets/Deratizare_img1.jpeg",
        InfoSection2Icon: "assets/Deratizare_icon2.svg",
        InfoSection2Title: "Soluții Personalizate și Durabile",
        InfoSection2Text: "Înțelegem că fiecare situație de infestare cu rozătoare este unică, motiv pentru care oferim soluții personalizate pentru nevoile specifice ale fiecărui client. De la evaluarea inițială a problemei până la implementarea măsurilor de prevenire a reapariției, lucrăm împreună cu clienții noștri pentru a dezvolta un plan eficient și durabil. Prin abordarea noastră orientată către client și angajamentul nostru față de rezultatele de calitate, ne asigurăm că fiecare client este complet satisfăcut cu serviciile noastre de deratizare.",
        InfoSection2Img: "assets/Deratizare_img2.jpeg",
        Service1Img: "assets/Dezinfectie_offer_img.jpeg",
        Service1Title: "Dezinfectie",
        Service1Text: " este un proces vital în menținerea sănătății și prevenirea răspândirii bolilor infecțioase. Această practică constă în...",
        Service1BigWord: "Dezinfectarea ",
        Service1Icon: "assets/Sol.svg",
        Service2Img: "assets/Dezinsectie_offer_img.jpeg",
        Service2Title: "Dezinsectie",
        Service2BigWord: "Dezinsecția ",
        Service2Text: "constă în eliminarea insectelor dăunătoare dintr-un anumit mediu, cum ar fi locuințele sau spațiile comerciale...",
        Service2Icon: "assets/Fly.svg",
    },
    {
        id: 1,
        nume: "Dezinsectie",
        headerImg: "assets/Dezinsectie_Hero.jpeg",
        headerText: "Ține insectele la distanță cu Derasovil: Soluții profesioniste pentru un mediu fără dăunători!",
        infoTitle: "Control Profesional Împotriva Insectelor",
        infoText: "Cu o experiență vastă și un palmares de succes în combaterea insectelor, Derasovil oferă servicii de dezinsecție de încredere și personalizate. Echipa noastră de specialiști înțelege nevoile specifice ale fiecărui client și utilizează tehnici adecvate pentru a elimina infestările cu insecte și a preveni reapariția lor. Alegeți Derasovil pentru a vă bucura de un mediu curat și protejat împotriva dăunătorilor.",
        CardImg: "assets/Ants_Card_Img.jpeg",
        CardBigWord: "Insectele ", 
        CardText: "reprezintă o amenințare constantă pentru locuințe și sănătatea publică. Infestările pot provoca daune materiale și pot transmite boli periculoase.",
        CardSection1Title: "Metode de Combatere:",
        CardSection1Text: "Dezinsecția utilizează substanțe chimice și tehnici de igienizare pentru a eradica insectele dintr-un mediu specific, garantând un control riguros al infestării.",
        CardSection2Title: "Prevenirea reapariției:",
        CardSection2Text: "Dezinsecția periodică nu numai că elimină infestările actuale, ci și previne reapariția lor, asigurând un mediu sigur lipsit de dăunători.",
        CardSection3Title: "Riscuri pentru sănătate:",
        CardSection3Text: "Infestarea cu insecte poate duce la contaminarea alimentelor, transmiterea de boli și deteriorarea proprietăților.",
        InfoSection1Icon: "assets/Deratizare_icon1.svg",
        InfoSection1Title: "Siguranță și Responsabilitate",
        InfoSection1Text: "Echipa noastră de specialiști calificați utilizează metode și substanțe sigure, respectând normele și standardele de siguranță în vigoare. De la evaluarea inițială a infestării până la implementarea soluțiilor de combatere a insectelor, ne concentrăm pe protejarea clienților noștri și a mediului înconjurător, asigurându-ne că procesul de dezinsecție este realizat în mod responsabil și profesional.",
        InfoSection1Img: "assets/Dezinsectie_Img1.jpeg",
        InfoSection2Icon: "assets/Deratizare_icon2.svg",
        InfoSection2Title: "Soluții Personalizate și Durabile",
        InfoSection2Text: "Derasovil oferă soluții personalizate și flexibile, adaptate nevoilor specifice ale fiecărui client. Înțelegem că fiecare situație de infestare cu insecte este unică, motiv pentru care dezvoltăm strategii de dezinsecție personalizate, ținând cont de tipul infestării, dimensiunea spațiului și preferințele clientului. Suntem dedicați furnizării de soluții durabile și eficiente, care să rezolve problemele cu insectele și să prevină reapariția lor în viitor.",
        InfoSection2Img: "assets/Dezinsectie_Img2.jpeg",
        Service1Img: "assets/Dezinfectie_offer_img.jpeg",
        Service1Title: "Dezinfectie",
        Service1Text: " este un proces vital în menținerea sănătății și prevenirea răspândirii bolilor infecțioase. Această practică constă în...",
        Service1BigWord: "Dezinfectarea ",
        Service1Icon: "assets/Sol.svg",
        Service2Img: "assets/Mouse_offer_img.jpeg",
        Service2Title: "Deratizare",
        Service2BigWord: "Deratizarea ",
        Service2Text: "este procesul de eliminare a rozătoarelor nedorite, precum șobolanii și șoarecii, dintr-un anumit mediu...",
        Service2Icon: "assets/Mice.svg",
    },
    {
        id: 2,
        nume: "Dezinsfectie",
        headerImg: "assets/Dezinfectie_Hero.jpeg",
        headerText: "Derasovil: Partenerul tău de încredere în lupta pentru un mediu sănătos.",
        infoTitle: "Soluții de dezinfecție pentru un mediu curat și sănătos",
        infoText: "Echipa noastră dedicată înțelege importanța unui mediu curat și sigur, motiv pentru care utilizăm cele mai avansate tehnologii și produse eficiente pentru eliminarea completă a microorganismelor nocive. Alegeți Derasovil pentru a vă asigura un spațiu protejat și sănătos pentru dumneavoastră și cei dragi.",
        CardImg: "assets/Dezinfectie_Card_Img.jpeg",
        CardBigWord: "Dezinfectarea ", 
        CardText: "eficientă contribuie la reducerea riscului de contaminare cu agenți patogeni, sporind astfel siguranța și sănătatea în spațiile tratate.",
        CardSection1Title: "Metode de Combatere:",
        CardSection1Text: "Metodele de combatere a agenților patogeni și a microbilor implică utilizarea substanțelor chimice dezinfectante, precum și tehnologii moderne precum ultravioletul și ozonul.",
        CardSection2Title: "Prevenirea reapariției:",
        CardSection2Text: "Prevenirea reapariției agenților patogeni și a microbilor necesită o igienizare regulată, menținerea unui mediu curat și monitorizarea constantă a condițiilor de igienă.",
        CardSection3Title: "Riscuri pentru sănătate:",
        CardSection3Text: "Expozitia la agenti patogeni prezinta riscuri pentru sanatate, incluzand infectii si boli transmisibile. Dezinfectarea si igienizarea regulata sunt cruciale pentru prevenirea acestora.",
        InfoSection1Icon: "assets/Deratizare_icon1.svg",
        InfoSection1Title: "Siguranță și Responsabilitate",
        InfoSection1Text: "Într-o lume marcată de provocări legate de sănătate, Derasovil se angajează să ofere servicii de dezinfectare care combină eficiența cu siguranța. . Fiecare intervenție este realizată cu atenție sporită la detalii și respect față de mediu, pentru a vă oferi nu doar un mediu curat, ci și unul sigur pentru toți cei care îl folosesc. Cu Derasovil, puteți avea încredere că siguranța dumneavoastră și a celor dragi este pe mâini sigure.",
        InfoSection1Img: "assets/Dezinfectie_Img1.jpeg",
        InfoSection2Icon: "assets/Deratizare_icon2.svg",
        InfoSection2Title: "Soluții Personalizate și Durabile",
        InfoSection2Text: "La Derasovil, ne concentrăm pe oferirea de soluții personalizate și durabile pentru nevoile dumneavoastră de dezinfectare. Înțelegem că fiecare spațiu are cerințe unice, motiv pentru care lucrăm îndeaproape cu clienții noștri pentru a dezvolta strategii personalizate, adaptate specific situației lor. Utilizăm tehnologii și produse durabile, care nu doar elimină amenințările microbiene, ci și contribuie la menținerea unui mediu curat și sănătos pe termen lung.",
        InfoSection2Img: "assets/Dezinfectie_Img2.jpeg",
        Service1Img: "assets/Dezinsectie_offer_img.jpeg",
        Service1Title: "Dezinsectie",
        Service1BigWord: "Dezinsecția ",
        Service1Text: "constă în eliminarea insectelor dăunătoare dintr-un anumit mediu, cum ar fi locuințele sau spațiile comerciale...",
        Service1Icon: "assets/Fly.svg",
        Service2Img: "assets/Mouse_offer_img.jpeg",
        Service2Title: "Deratizare",
        Service2BigWord: "Deratizarea ",
        Service2Text: "este procesul de eliminare a rozătoarelor nedorite, precum șobolanii și șoarecii, dintr-un anumit mediu...",
        Service2Icon: "assets/Mice.svg",
    }
 ];

export default info;